name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: self-hosted
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-8u402-b06_1.9.9_2.13.13
      options: --user 1001:1001
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: sbt clean +test
